# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
changelog:
  disable: true
builds:
  - binary: tweety
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md
      - LICENSE-MIT
release:
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
brews:
  - name: tweety
    homepage: https://github.com/pomdtr/tweety
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "tweety"
    post_install: |-
      system "#{bin}/tweety", "install", "--overwrite"
