# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion "bash" >./completions/tweety.bash'
    - sh -c 'go run . completion "zsh" >./completions/tweety.zsh'
    - sh -c 'go run . completion "fish" >./completions/tweety.fish'
changelog:
  disable: true
builds:
  - binary: tweety
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: "tweety-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
release:
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
brews:
  - name: tweety
    homepage: https://github.com/pomdtr/tweety
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "tweety"
      bash_completion.install "completions/tweety.bash"
      zsh_completion.install "completions/tweety.zsh"
      fish_completion.install "completions/tweety.fish"
    post_install: |-
      system "#{bin}/tweety", "install", "extension", "--overwrite", "#{share}/tweety/extensions/chrome"
    caveats: |
      After installation, run:
        tweety install manifest
