name: release

on:
  push:
    # run only against tags
    tags:
      - "v*.*.*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "extension/package-lock.json"
      - name: Set VERSION env var
        run: echo "VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')" >> $GITHUB_ENV
      - name: Build extension
        run: npm ci && npm run build && npm run zip:firefox
        working-directory: extension
        env:
          MANIFEST_VERSION: ${{ env.VERSION }}
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.4"
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
